Repository Event-Structures/event-struct, pull requests merged in 2020-12, with the labels that each got.

#32 ci: fix finmap dependencies
  .github/workflows/ci.yml
  coq-event-struct.opam
Labels: CI

#31 regmachine via Rfsfun
  eventstructure.v
  regmachine.v
  transitionsystem.v
Labels: enhancement

#35 feat: add seq_in
  regmachine.v
  utilities.v
Labels: enhancement

#37 doc: fix description in opam file
  coq-event-struct.opam
Labels: documentation

#40 doc[opam]: keywords, classification, authors
  coq-event-struct.opam
Labels: documentation
